# Generated by Django 3.1.1 on 2020-12-09 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_Bank_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_Code', models.CharField(default='wct000', max_length=100)),
                ('Bankname', models.CharField(default=None, max_length=50)),
                ('Account_NO', models.CharField(default=None, max_length=100)),
                ('IFSC_Code', models.CharField(default=None, max_length=100)),
                ('Branch', models.CharField(default=None, max_length=100)),
                ('Registerd_Mobile', models.CharField(default=None, max_length=30)),
                ('GooglePayNo', models.CharField(default=None, max_length=100)),
                ('EName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
            ],
        ),
    ]
