# Generated by Django 3.1.1 on 2020-12-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp_Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Date', models.DateTimeField()),
                ('Employee_Code', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Application_Type', models.CharField(choices=[('', 'Select Leave Type'), ('m', 'Sick Leave'), ('e', 'Emergency Leave'), ('p', 'Paid Leave'), ('u', 'Unpaid Leave')], max_length=5)),
                ('From', models.CharField(max_length=20)),
                ('To', models.CharField(max_length=52)),
                ('Department', models.CharField(choices=[('', 'Select to Report'), ('H', 'HR'), ('t', 'TL'), ('m', 'MD')], default='HR', max_length=10)),
            ],
        ),
    ]
